In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

In [41]:
data_path = Path().cwd() / 'data'
data_df = pd.read_csv(data_path / 'transactions_obf.csv', parse_dates=['transactionTime'])
data_df.head()

,transactionTime,eventId,accountNumber,merchantId,mcc,merchantCountry,merchantZip,posEntryMode,transactionAmount,availableCash
0,2017-01-01 00:00:00+00:00,18688431A1,94f9b4e7,b76d06,5968,826,CR0,1,10.72,7500
1,2017-01-01 00:49:03+00:00,2164986A1,648e19cf,718cc6,5499,826,DE14,81,21.19,4500
2,2017-01-01 00:43:17+00:00,31294145A1,c0ffab1b,94cafc,5735,442,NaN,81,5.04,9500
3,2017-01-01 00:15:07+00:00,11162049A1,038099dd,7d5803,5499,826,NR1,81,21.00,7500
4,2017-01-01 00:37:09+00:00,17067235A1,3130363b,12ca76,5411,826,M50,81,47.00,10500

In [7]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118621 entries, 0 to 118620
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   transactionTime    118621 non-null  datetime64[ns, UTC]
 1   eventId            118621 non-null  object
 2   accountNumber      118621 non-null  object
 3   merchantId         118621 non-null  object
 4   mcc                118621 non-null  int64
 5   merchantCountry    118621 non-null  int64
 6   merchantZip        95616 non-null   object
 7   posEntryMode       118621 non-null  int64
 8   transactionAmount  118621 non-null  float64
 9   availableCash      118621 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(1), int64(4), object(4)
memory usage: 9.1+ MB

In [8]:
print(f'Number of unique entries:\n{data_df.nunique().sort_values(ascending=False)}')

Number of unique entries:
eventId              118621
transactionTime      118105
merchantId            33327
transactionAmount     16431
merchantZip            3260
accountNumber           766
mcc                     361
merchantCountry          82
availableCash            19
posEntryMode             10
dtype: int64

In [21]:
print(f'Percentage of missing values:\n{data_df.isnull().sum()}')

Percentage of missing values:
transactionTime          0
eventId                  0
accountNumber            0
merchantId               0
mcc                      0
merchantCountry          0
merchantZip          23005
posEntryMode             0
transactionAmount        0
availableCash            0
dtype: int64

In [10]:
data_path = Path().cwd() / 'data'
labels_df = pd.read_csv(data_path / 'labels_obf.csv', parse_dates=['reportedTime'])
labels_df.head()

               reportedTime      eventId
0 2017-01-04 00:00:00+00:00  101536329A1
1 2017-01-04 00:00:00+00:00  101536425A1
2 2017-01-04 00:00:00+00:00  101536473A1
3 2017-01-04 00:00:00+00:00  101536617A1
4 2017-01-04 00:00:00+00:00  101536761A1

In [11]:
labels_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 875 entries, 0 to 874
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reportedTime  875 non-null    datetime64[ns, UTC]
 1   eventId       875 non-null    object
dtypes: datetime64[ns, UTC](1), object(1)
memory usage: 13.8+ KB

In [12]:
print(f'Number of unique entries in labels dataset:\n{labels_df.nunique()}')

Number of unique entries in labels dataset:
reportedTime    145
eventId         875
dtype: int64

In [52]:
data_df['fraudCase'] = data_df.eventId.isin(labels_df.eventId).astype(int)

In [53]:
data_df.head()

,transactionTime,eventId,accountNumber,merchantId,mcc,merchantCountry,merchantZip,posEntryMode,transactionAmount,availableCash,fraud
0,2017-01-01 00:00:00+00:00,18688431A1,94f9b4e7,b76d06,5968,826,CR0,1,10.72,7500,0
1,2017-01-01 00:49:03+00:00,2164986A1,648e19cf,718cc6,5499,826,DE14,81,21.19,4500,0
2,2017-01-01 00:43:17+00:00,31294145A1,c0ffab1b,94cafc,5735,442,NaN,81,5.04,9500,0
3,2017-01-01 00:15:07+00:00,11162049A1,038099dd,7d5803,5499,826,NR1,81,21.00,7500,0
4,2017-01-01 00:37:09+00:00,17067235A1,3130363b,12ca76,5411,826,M50,81,47.00,10500,0

In [54]:
neg, pos = np.bincount(data_df['fraud'])
total = neg + pos
print('Examples:\n    Total: {}\n    Positive: {} ({:.2f}% of total)\n'.format(
    total, pos, 100 * pos / total))

Examples:
    Total: 118621
    Positive: 875 (0.74% of total)